asd/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^details/(?P<file_id>\d+)/$', views.details, name='details'),
    url(r'^uploads/$', views.uploads, name='uploads'),
    url(r'^delete/(?P<file_id>\d+)/$', views.delete, name='delete'),
    url(r'^download/(?P<link>\w+)/$', views.download, name='download'),
]

asd_test/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('asd.urls', namespace='asd')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

asd/models.py
import os
import uuid
import shutil

from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


def user_directory_path(instance, filename):
    ext = os.path.splitext(filename)[1]
    fname = str(uuid.uuid4()) + ext
    prefix = 'user_{0}'.format(instance.owner.id)
    return os.path.join(prefix, fname)


class DFile(models.Model):
    owner = models.ForeignKey(User)
    path = models.FileField(upload_to=user_directory_path)
    filename = models.CharField(max_length=256)
    sha_sum = models.CharField(max_length=50, editable=False, default=None)
    link = models.BooleanField(default=False)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['uploaded_at', 'filename']

    def delete(self, *args, **kwargs):
        try:
            this_record = DFile.objects.get(id=self.id)
        except (DFile.DoesNotExist, ValueError):
            pass
        else:
            if not this_record.link:
                try:
                    link = DFile.objects.filter(sha_sum=this_record.sha_sum)[0]
                except IndexError:
                    this_record.path.delete()
                else:
                    os.makedirs(os.path.join(settings.MEDIA_ROOT, 'user_{0}'.format(link.owner.id)), exist_ok=True)

                    new_path_list = list(os.path.split(str(this_record.path)))
                    new_path_list[0] = 'user_{0}'.format(link.owner.id)
                    new_path = os.path.join(new_path_list[0], new_path_list[1])

                    shutil.move(
                        os.path.join(settings.MEDIA_ROOT, str(this_record.path)),
                        os.path.join(settings.MEDIA_ROOT, new_path)
                    )

                    link.path = new_path
                    link.link = 0
                    link.save()

                    DFile.objects.filter(
                        sha_sum=this_record.sha_sum,
                        link=True
                    ).update(path=new_path)
        finally:
            super(DFile, self).delete(*args, **kwargs)

users/models.py
from django.db import models

# Create your models here.

asd/forms.py
from django import forms


class DFileForm(forms.Form):
    file = forms.FileField(
        label='ВЫберите файл',
        error_messages={'required': 'Укажите файл!'},
    )

asd/views.py
from django.shortcuts import render
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.conf import settings

import os
import hashlib

from .models import DFile
from .forms import DFileForm


@login_required
def index(request):
    files = DFile.objects.filter(owner=request.user).all()
    context = {'files': files}
    return render(request, 'asd/index.html', context)


@login_required
def uploads(request):
    count = DFile.objects.all().count()
    if count > 100:
        msg = "Превышение количества файлов (100)!"
        messages.warning(request, msg)
        return HttpResponseRedirect(reverse('asd:index'))
    if request.method == 'POST':
        form = DFileForm(request.POST, request.FILES)
        if form.is_valid():
            newfile = DFile(path=request.FILES['file'])
            newfile.owner = request.user
            newfile.filename = request.FILES['file'].name

            sha = hashlib.sha1()
            for chunk in newfile.path.chunks():
                sha.update(chunk)
            newfile.sha_sum = sha.hexdigest()
            files = DFile.objects.filter(
                    sha_sum=newfile.sha_sum,
                    link=False
                )
            msg = "Файл {0} загружен!".format(newfile.filename)
            for file in files:
                newfile.path = file.path
                newfile.link = True
                msg = "Файл {0} найден у другого пользователя!".format(newfile.filename)
                if file.owner == newfile.owner:
                    msg = "Файл {0} у вас уже есть и имеет имя {1}!".format(newfile.filename, file.filename)
                    messages.warning(request, msg)
                    return HttpResponseRedirect(reverse('asd:index'))
                # Проверка на существование ссылок на загружаемый файл
                # если ссылка на этот файл уже существует у данного пользователя
                link_files = DFile.objects.filter(
                    sha_sum=newfile.sha_sum,
                    owner=newfile.owner
                )
                for link_file in link_files:
                    msg = "Файл {0} у вас уже есть и имеет имя {1}!".format(newfile.filename, file.filename)
                    messages.warning(request, msg)
                    return HttpResponseRedirect(reverse('asd:index'))
            newfile.save()
            messages.success(request, msg)
            return HttpResponseRedirect(reverse('asd:index'))
    else:
        form = DFileForm()

    context = {'form': form}
    return render(request, 'asd/uploads.html', context)


@login_required
def details(request, file_id):
    file = DFile.objects.filter(owner=request.user).get(id=file_id)
    context = {'file': file}
    return render(request, 'asd/details.html', context)


@login_required
def delete(request, file_id):
    try:
        file = DFile.objects.get(owner=request.user, id=file_id)
        filename = file.filename
        file.delete()
        messages.info(request, "Файл {0} удалён!".format(filename))
    except DFile.DoesNotExist:
        messages.info(request, "Файл не найден!")
    return HttpResponseRedirect(reverse('asd:index'))


def download(request, link):
    try:
        file = DFile.objects.get(sha_sum=link, link=False)
    except:
        messages.info(request, "Файл не найден!")
        return HttpResponseRedirect(reverse('asd:index'))

    file_path = os.path.join(settings.MEDIA_ROOT, str(file.path))
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = 'inline; filename=' + file.filename
            return response

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    """Завершает сеанс работы с приложением."""
    logout(request)
    return HttpResponseRedirect(reverse('asd:index'))


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('asd:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

asd/templates/asd/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Learning Log</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{% url 'asd:index' %}">Файловое хранилище</a>
                {% if user.is_authenticated %}
                    <a class="navbar-brand" href="{% url 'asd:uploads' %}"><span class="glyphicon glyphicon-skull"></span>Загрузить</a>
                {% endif %}
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a>Привет, {{ user.username }}.</a></li>
                        <li><a href="{% url 'users:logout' %}">log out</a></li>
                    {% else %}
                        <li><a href="{% url 'users:register' %}">register</a></li>
                        <li><a href="{% url 'users:login' %}">log in</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div>
</body>
</html>

asd/templates/asd/details.html
{% extends 'asd/base.html' %}

{% block content %}
<p>sha сумма: {{ file.comment }}</p>
<p>путь: {{ file.path }}</p>
{% endblock content %}

asd/templates/asd/index.html
{% extends "asd/base.html" %}

{% block header %}
{% if messages %}
    {% for message in messages %}
      <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
    {% endfor %}
  {% endif %}
{% endblock header %}

{% block content %}
    <table class="table">
        <thead class="thead-inverse">
            <tr>
                <th>#</th>
                <th>Имя файла</th>
                <th>Действия</th>
            </tr>
        </thead>
    <tbody>
        {% for file in files %}
        <tr>
            <th>{{ loop.index }}</th>
            <td>
                <a href="{% url 'asd:details' file.id %}">
                    {{ file.filename }}
                </a>
            </td>
            <td>
                <a href="{% url 'asd:delete' file.id %}"><span class="glyphicon glyphicon-bin">Удалить</span></a>
                <a href="{% url 'asd:download' file.sha_sum %}"><span class="glyphicon glyphicon-cloud-download">Скачать</span></a>
            </td>
        </tr>
        {% empty %}
            <tr><td>No files.</td></tr>
        {% endfor %}
    </tbody>
    </table>
{% endblock content %}

asd/templates/asd/uploads.html
{% extends 'asd/base.html' %}
{% load bootstrap3 %}

{% block header%}
<h2>Загрузить изображение</h2>
{% endblock header %}

{% block content %}
<form action="{% url 'asd:uploads' %}" method="post" enctype="multipart/form-data" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Загрузить</button>
        {% endbuttons %}
</form>
{% endblock content %}

users/templates/users/login.html
{% extends 'asd/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}
    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Log in</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'asd:index' %}" />
    </form>

{% endblock content %}

users/templates/users/register.html
{% extends 'asd/base.html' %}
{% load bootstrap3 %}

{% block content %}
    <form method="post" action="{% url 'users:register' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Log in</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'asd:index' %}" />
    </form>

{% endblock content %}